spring:
  application:
    name: billing
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${usernameDB}
    url: ${url}
    password: ${passwordDB}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: 'true'