spring:
  application:
    name: billing
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    url: ${SPRING_DATASOURCE_URL}
    password: ${PASSWORD_DB}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: 'true'

email:
  from: ${EmailFrom}
  password: ${PASSWORD_MAIL}